In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

ModuleNotFoundError: No module named 'sklearn'

In [2]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.26.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting numpy>=1.24.1 (from scikit-learn)
  Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Downloading scikit_learn-1.9.1-cp311-cp311-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ------------ --------------------------- 2.6/8.3 MB 15.1 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.3 MB 14.8 MB/s eta 0:00:01
   ----------------------- ---------------- 5.0/8.3 MB 8.4 MB/s eta 0:00:01
   --------------------------- ------------ 5.8/8.3 MB 7.2 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.3 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 7.1/8.3 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 5.7 MB/s  0:00:01
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
    --------------------------------------- 0.8/36.6 MB 4.8 MB/s eta 0:00:08
   -- ------------------------------------- 2.1/36.6 MB 5.3 MB/s eta 0:00:07
   --- ------------------------------------ 3.1/36.6 MB 5.6 MB/s eta 0:00:06
   ---- ----------------------------------- 4.2/36.6 MB 5.4 MB/s eta 0:00:07
   ----- ---------------------------------- 4.7/36.6 MB 4.8 MB/s eta 0:00:07
   ------ --------------------------------- 5.8/36.6 MB 4.8 MB/s eta 0:00:07
   ------- -------------------------------- 6.8/36.6 MB 4.9 MB/s eta 0:00:07
   -------- ------------------------------- 7.6/36.6 MB 4.7 MB/s eta 0:00:07
   --------- ------------------------------ 8.7/36.6 MB 4.8 MB/s eta 0:00:06
   ---------- ----------------------------- 9.7/36.6 MB 4.7 MB/s eta 0:00:06
   ----------- ---------------------------- 10.2/36.6 MB 4.5 MB/s eta 0:00:06
   ------------ --------------------------- 11.0/36.6 MB 4.4 MB/s eta 0:00:06
   ------------- -------------------------- 12.3/36.6 MB 4.5 MB/s eta 0:00:06
   -------------- ------------------------- 13.4/36.6 MB 4.6 MB/s eta 0:00:06
   --------------- ------------------------ 14.4/36.6 MB 4.6 MB/s eta 0:00:05
   ---------------- ----------------------- 15.2/36.6 MB 4.5 MB/s eta 0:00:05
   ----------------- ---------------------- 16.0/36.6 MB 4.5 MB/s eta 0:00:05
   ------------------ --------------------- 16.8/36.6 MB 4.5 MB/s eta 0:00:05
   ------------------- -------------------- 17.6/36.6 MB 4.4 MB/s eta 0:00:05
   -------------------- ------------------- 18.4/36.6 MB 4.3 MB/s eta 0:00:05
   --------------------- ------------------ 19.4/36.6 MB 4.4 MB/s eta 0:00:04
   ---------------------- ----------------- 21.0/36.6 MB 4.6 MB/s eta 0:00:04
   ----------------------- ---------------- 21.8/36.6 MB 4.5 MB/s eta 0:00:04
   ------------------------ --------------- 22.3/36.6 MB 4.5 MB/s eta 0:00:04
   ------------------------- -------------- 23.1/36.6 MB 4.4 MB/s eta 0:00:04
   -------------------------- ------------- 24.1/36.6 MB 4.4 MB/s eta 0:00:03
   ---------------------------- ----------- 25.7/36.6 MB 4.5 MB/s eta 0:00:03
   ----------------------------- ---------- 26.7/36.6 MB 4.6 MB/s eta 0:00:03
   ----------------------------- ---------- 27.0/36.6 MB 4.4 MB/s eta 0:00:03
   ------------------------------ --------- 27.8/36.6 MB 4.4 MB/s eta 0:00:02
   ------------------------------- -------- 28.8/36.6 MB 4.4 MB/s eta 0:00:02
   -------------------------------- ------- 29.9/36.6 MB 4.6 MB/s eta 0:00:02
   ---------------------------------- ----- 31.2/36.6 MB 4.5 MB/s eta 0:00:02
   ----------------------------------- ---- 32.2/36.6 MB 4.5 MB/s eta 0:00:01
   ------------------------------------ --- 33.0/36.6 MB 4.5 MB/s eta 0:00:01
   ------------------------------------- -- 34.1/36.6 MB 4.5 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.6 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.6 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 4.2 MB/s  0:00:08
Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.6 MB 8.4 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 8.4 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 6.9 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 6.0 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 6.1 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 6.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 6.1 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 5.9 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 5.5 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 5.5 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 5.1 MB/s  0:00:02
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, numpy, narwhals, cloudpickle, scipy, joblib, scikit-learn

  Attempting uninstall: numpy

    Found existing installation: numpy 1.26.1

   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
    Uninstalling numpy-1.26.1:
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
      Successfully uninstalled numpy-1.26.1
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----- ---------------------------------- 1/7 [numpy]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------------- ----------- 5/7 [joblib]
   ---------------------------- ----------- 5/7 [joblib]
   ---------------------------- ----------- 5/7 [joblib]
   ---------------------------- ----------- 5/7 [joblib]
   ---------------------------- ----------- 5/7 [joblib]
   ---------------------------- ----------- 5/7 [joblib]
   ---------------------------- ----------- 5/7 [joblib]
   ---------------------------- ----------- 5/7 [joblib]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages\~umpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.1.1 requires numpy<2.0,>=1.16; python_version <= "3.11", but you have numpy 2.4.6 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.4.6 which is incompatible.
pandas 2.1.3 requires numpy<2,>=1.23.2; python_version == "3.11", but you have numpy 2.4.6 which is incompatible.

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: C:\Users\himan\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py:14: UserWarning: A NumPy version >=1.26.4 and <2.7.0 is required for this version of SciPy (detected version 1.26.1)
  from scipy.sparse import csr_array, issparse

ImportError: cannot load module more than once per process

ImportError: numpy._core.multiarray failed to import

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

ImportError: cannot load module more than once per process

ImportError: numpy._core.multiarray failed to import

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [2]:
pip install --upgrade pandas numpy

Requirement already satisfied: pandas in C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.1.3)
Collecting pandas
  Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------- ----------------------------- 2.6/9.9 MB 18.9 MB/s eta 0:00:01
   ------------------ --------------------- 4.5/9.9 MB 12.8 MB/s eta 0:00:01
   ------------------- -------------------- 4.7/9.9 MB 8.7 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.9 MB 7.1 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 6.7 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 5.9 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 6.3 MB/s  0:00:01
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.1.3
    Uninstalling pandas-2.1.3:
      Successfully uninstalled pandas-2.1.3
Successfully installed pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\himan\AppData\Local\Programs\Python\Python311\Lib\site-packages\~andas'.
  You can safely remove it manually.

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: C:\Users\himan\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.info

<bound method DataFrame.info of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [5]:
if 'Customer ID' in df.columns:
    df = df.drop(columns=['Customer ID'])

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     3900 non-null   int64
 1   Gender                  3900 non-null   str
 2   Item Purchased          3900 non-null   str
 3   Category                3900 non-null   str
 4   Purchase Amount (USD)   3900 non-null   int64
 5   Location                3900 non-null   str
 6   Size                    3900 non-null   str
 7   Color                   3900 non-null   str
 8   Season                  3900 non-null   str
 9   Review Rating           3863 non-null   float64
 10  Subscription Status     3900 non-null   str
 11  Shipping Type           3900 non-null   str
 12  Discount Applied        3900 non-null   str
 13  Promo Code Used         3900 non-null   str
 14  Previous Purchases      3900 non-null   int64
 15  Payment Method          3900 non-null   str
 16  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(3), str(13)
memory usage: 518.1 KB

In [11]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     3900 non-null   int64
 1   Gender                  3900 non-null   str
 2   Item Purchased          3900 non-null   str
 3   Category                3900 non-null   str
 4   Purchase Amount (USD)   3900 non-null   int64
 5   Location                3900 non-null   str
 6   Size                    3900 non-null   str
 7   Color                   3900 non-null   str
 8   Season                  3900 non-null   str
 9   Review Rating           3900 non-null   float64
 10  Subscription Status     3900 non-null   str
 11  Shipping Type           3900 non-null   str
 12  Discount Applied        3900 non-null   str
 13  Promo Code Used         3900 non-null   str
 14  Previous Purchases      3900 non-null   int64
 15  Payment Method          3900 non-null   str
 16  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(3), str(13)
memory usage: 518.1 KB

In [9]:
df.isnull().sum(.)

SyntaxError: invalid syntax (1404869196.py, line 1)

In [13]:
df.isnull().sum()

Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [14]:
# 4. Feature Encoding (One-Hot Encoding for categorical text columns)
X = pd.get_dummies(df.drop(columns=['Subscription Status']), drop_first=True)
y = df['Subscription Status'].apply(lambda x: 1 if x == 'Yes' else 0)

In [15]:
# Stratified Train-Test Split (maintaining the 27% positive class ratio)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [16]:
display(df.head())

,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [17]:
print(df.isnull().sum())

Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [18]:
# View the transformed feature dataset with one-hot encoded columns
display(X.head())

,Age,Purchase Amount (USD),Review Rating,Previous Purchases,Gender_Male,Item Purchased_Belt,Item Purchased_Blouse,Item Purchased_Boots,Item Purchased_Coat,Item Purchased_Dress,...,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_PayPal,Payment Method_Venmo,Frequency of Purchases_Bi-Weekly,Frequency of Purchases_Every 3 Months,Frequency of Purchases_Fortnightly,Frequency of Purchases_Monthly,Frequency of Purchases_Quarterly,Frequency of Purchases_Weekly
0,55,53,3.1,14,True,False,True,False,False,False,...,False,False,False,True,False,False,True,False,False,False
1,19,64,3.1,2,True,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,50,73,3.1,23,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True
3,21,90,3.5,49,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
4,45,49,2.7,31,True,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [19]:
# Check the target variable mapping and counts
print(y.value_counts())

Subscription Status
0    2847
1    1053
Name: count, dtype: int64

In [20]:
print("Training data shape (Features):", X_train.shape)
print("Testing data shape (Features):", X_test.shape)

Training data shape (Features): (3120, 129)
Testing data shape (Features): (780, 129)

In [21]:
# Check the proportion of 1s and 0s in the training set
print("\ny_train class distribution:")
print(y_train.value_counts(normalize=True))

y_train class distribution:
Subscription Status
0    0.730128
1    0.269872
Name: proportion, dtype: float64

In [22]:
# Check the proportion of 1s and 0s in the testing set
print("\ny_test class distribution:")
print(y_test.value_counts(normalize=True))

y_test class distribution:
Subscription Status
0    0.729487
1    0.270513
Name: proportion, dtype: float64

In [24]:
#Training Random Forest & Logistic Regression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

In [25]:
# --- MODEL A: Random Forest ---

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

rf_preds = rf_model.predict(X_test)
rf_probs = rf_model.predict_proba(X_test)[:, 1]

print(f"Random Forest Accuracy: {accuracy_score(y_test, rf_preds):.4f}")
print(f"Random Forest ROC-AUC:  {roc_auc_score(y_test, rf_probs):.4f}")

Random Forest Accuracy: 0.8487
Random Forest ROC-AUC:  0.9054

In [26]:
# --- MODEL B: Logistic Regression (Requires Scaled Data) ---
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train_scaled, y_train)

lr_preds = lr_model.predict(X_test_scaled)
lr_probs = lr_model.predict_proba(X_test_scaled)[:, 1]

print(f"\nLogistic Regression Accuracy: {accuracy_score(y_test, lr_preds):.4f}")
print(f"Logistic Regression ROC-AUC:  {roc_auc_score(y_test, lr_probs):.4f}")

Logistic Regression Accuracy: 0.8513
Logistic Regression ROC-AUC:  0.9097

In [27]:
# Inspect top positive and negative coefficients from Logistic Regression
coefficients = pd.Series(lr_model.coef_[0], index=X.columns).sort_values(ascending=False)
print("\nTop Positive Drivers (Increased Likelihood of Subscribing):")
print(coefficients.head(5))

print("\nTop Negative Drivers (Decreased Likelihood):")
print(coefficients.tail(5))

Top Positive Drivers (Increased Likelihood of Subscribing):
Promo Code Used_Yes     1.921938
Discount Applied_Yes    1.921938
Gender_Male             0.528611
Location_Kentucky       0.156988
Location_Nevada         0.154992
dtype: float64

Top Negative Drivers (Decreased Likelihood):
Season_Spring                      -0.098134
Frequency of Purchases_Quarterly   -0.107534
Item Purchased_Jewelry             -0.110466
Item Purchased_Blouse              -0.128528
Season_Summer                      -0.133172
dtype: float64

In [28]:
# Exporting Predictions for Power BI
# Create a results DataFrame mapped back to the test subset
test_results = df.loc[X_test.index].copy()

# Add the probability scores from Random Forest (or Logistic Regression)
test_results['Subscription_Probability'] = rf_probs

# Segment customers into actionable Propensity Tiers
test_results['Propensity_Tier'] = pd.cut(
    test_results['Subscription_Probability'],
    bins=[-0.1, 0.4, 0.7, 1.0],
    labels=['Low Propensity', 'Medium Propensity', 'High Propensity']
)

# Export to CSV for Power BI consumption
test_results.to_csv('customer_subscription_predictions.csv', index=False)
print("\nSuccessfully exported prediction file: customer_subscription_predictions.csv")

Successfully exported prediction file: customer_subscription_predictions.csv

In [29]:
df.head()

,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [32]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"        # default user
password = "1234" # the password you set during installation
host = "localhost"           # if running locally
port = "5432"                # default PostgreSQL port
database = "customer_behavior"     # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"     # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.